### PR TITLE
Avoid matching in a word in is_write_query()

### PR DESCRIPTION
**Pull request by takotakot**

### CODE REVIEW

**Comment by JJJ** [comment]
@spacedmonkey just going through PRs. Any more thoughts on this one?

We really need to get unit tests setup and working. Wanna take that on, too?

**Comment by spacedmonkey** [comment]
I don’t want to merge this without unit test. I will add unit tests to ci in another pr

**Comment by JJJ** [comment]
@spacedmonkey understandable. I did just merge #100 which is going to conflict with this PR. Sorry about that.

**Comment by amitaymolko** [comment]
On master:  
`is_write_query("SELECT option_name, option_value FROM wp_options WHERE autoload = 'yes'");`  
returns true.  
With this fix, it returns false

**Comment by JJJ** [comment]
@amitaymolko That's a good thing!

**Comment by amitaymolko** [comment]
@JJJ 
Yeah, the fix is good, it reduces the load on the write servers.

**Comment by JJJ** [comment]
Merged to master. This is working fine for me, too.

**Pull request merged**
